"""Stdlib-only preflight. Import/GPU probes run in bounded, disposable children.

No model weights are opened, downloaded or generated by this checker.
"""
import argparse
import importlib
import json
import os
from pathlib import Path
import platform
import shutil
import subprocess
import sys
import tempfile
from concurrent.futures import ThreadPoolExecutor, as_completed
from urllib.request import Request, build_opener, ProxyHandler

PACKAGES = ('torch', 'torchvision', 'transformers', 'diffusers', 'accelerate', 'PIL',
            'psutil', 'filelock', 'safetensors', 'huggingface_hub', 'numpy', 'tokenizers')
LABELS = {'PIL': 'Pillow', 'huggingface_hub': 'Hugging Face Hub'}


def record(key, title, state, detail='', required=True):
    return dict(id=key, title=title, state=state, detail=detail, required=required)


def emit(value):
    print(json.dumps(value, ensure_ascii=False), flush=True)


def inspect_child(name):
    if name == 'cuda-stack':
        inspect_child('torch')
        inspect_child('torchvision')
        return inspect_child('gpu')
    if name == 'dependencies':
        from runtime_dependencies import check_dependencies
        return check_dependencies()
    if name == 'pipeline':
        import inspect
        from diffusers import QwenImage21Pipeline, AutoencoderKLQwenImage21
        parameters = inspect.signature(QwenImage21Pipeline.__call__).parameters
        needed = {'prompt', 'image', 'width', 'height', 'num_inference_steps', 'callback_on_step_end', 'negative_prompt', 'true_cfg_scale', 'output_resolution', 'use_kv_cache'}
        if not needed.issubset(parameters):
            raise RuntimeError('当前 Diffusers 不支持所需的图像接口。')
        source=inspect.getsource(QwenImage21Pipeline._get_qwen_prompt_embeds)
        if 'norm.register_forward_hook' not in source:
            raise RuntimeError('当前文字编码接口与固定版本不一致，请修复环境。')
        return 'QwenImage21Pipeline / FP32 VAE / text encoder fix'
    if name == 'enhancer':
        from transformers import AutoModelForImageTextToText, AutoProcessor, Qwen3_5ForConditionalGeneration
        return 'Qwen3.5 / PE-T2I / PE-I2I'
    if name == 'gpu':
        import torch
        torch.set_num_threads(1)
        if platform.system() == 'Darwin':
            if not torch.backends.mps.is_built():
                raise RuntimeError('当前 PyTorch 不含 Metal 支持，请修复依赖。')
            if not torch.backends.mps.is_available():
                raise RuntimeError('未检测到可用的 Apple GPU。')
            device = 'mps'
            label = 'Apple Metal / MPS'
        else:
            if torch.version.cuda is None:
                raise RuntimeError('当前 PyTorch 不含 CUDA 支持，请修复依赖。')
            if not torch.cuda.is_available():
                raise RuntimeError('未检测到可用的 NVIDIA CUDA GPU。')
            if not torch.cuda.is_bf16_supported():
                raise RuntimeError('当前显卡不支持模型所需的 BF16。')
            device = 'cuda'
            label = torch.cuda.get_device_name(0)
        # A few bytes confirm that the driver executes work. This is not model inference.
        value = torch.ones((2, 2), device=device, dtype=torch.bfloat16)
        if (value @ value).float().cpu().tolist() != [[2., 2.], [2., 2.]]:
            raise RuntimeError('GPU 基础运算检查失败。')
        return label
    module = importlib.import_module(name)
    if name in ('torch','torchvision','transformers'):
        from packaging.version import Version
        minimum={'torch':'2.9.0','torchvision':'0.24.0','transformers':'5.17.0'}[name]
        if Version(module.__version__)<Version(minimum):raise RuntimeError(f'{name} >= {minimum} is required')
    return str(getattr(module, '__version__', '已安装'))


def run_child(name, timeout=60):
    result = subprocess.run([sys.executable, '-X', 'utf8', str(Path(__file__).resolve()), '--check', name],
        capture_output=True, text=True, encoding='utf-8', errors='replace', timeout=timeout,
        creationflags=getattr(subprocess, 'CREATE_NO_WINDOW', 0),
        env={**os.environ, 'HF_HUB_OFFLINE': '1', 'TRANSFORMERS_OFFLINE': '1',
             'HF_HUB_DISABLE_TELEMETRY': '1', 'PYTHONUTF8': '1',
             'OMP_NUM_THREADS': '1', 'MKL_NUM_THREADS': '1'})
    lines = result.stdout.strip().splitlines()
    try:
        report = json.loads(lines[-1])
    except (ValueError, IndexError):
        diagnostic=(result.stderr or result.stdout).strip()[-1500:]
        raise RuntimeError(f'依赖检查进程退出 (exit {result.returncode})。\n{diagnostic}')
    if result.returncode or not report.get('ok'):
        raise RuntimeError(report.get('error', '依赖无法加载。'))
    return report['detail']


def collect(data, check=run_child, opener=None):
    """Yield each status change; failed checks never become successes by omission."""
    valid = (3, 10) <= sys.version_info[:2] < (3, 14) and sys.maxsize > 2**32
    yield record('python', 'Python 运行环境', 'pass' if valid else 'fail', platform.python_version() if valid else '需要 64 位 Python 3.10–3.13。')
    try:
        data.mkdir(parents=True, exist_ok=True)
        with tempfile.TemporaryFile(dir=data) as f:
            f.write(b'studio');f.flush()
        yield record('storage', '本地存储', 'pass', '可以保存会话与图片')
    except OSError:
        yield record('storage', '本地存储', 'fail', '无法写入数据目录，请检查磁盘和权限。')
    def inspect(name):
        title = {'dependencies': '依赖完整性', 'pipeline': '图像推理接口', 'enhancer': '提示词增强接口', 'gpu': 'GPU 加速'}.get(name, LABELS.get(name, name))
        key = name if name in ('dependencies', 'pipeline', 'enhancer', 'gpu') else 'package:' + name
        try:
            detail = check(name)
            return record(key, title, 'pass', detail, name!='enhancer')
        except subprocess.TimeoutExpired:
            return record(key, title, 'optional' if name=='enhancer' else 'fail', '检测超时，请重试或修复环境。', name!='enhancer')
        except Exception as error:
            # Keep upstream diagnostics visible in Details, not in the application copy.
            value = record(key, title, 'optional' if name=='enhancer' else 'fail', '增强接口不可用；不影响直接生图或改图。' if name=='enhancer' else '无法加载，请安装或修复依赖。', name!='enhancer')
            value['diagnostic'] = str(error)[:1500]
            return value
    # Imports remain isolated, but independent checks no longer repeat serially.
    names=(*PACKAGES, 'dependencies', 'pipeline', 'enhancer', 'gpu')
    with ThreadPoolExecutor(max_workers=4) as pool:
        futures=[]
        for name in names:
            title={'dependencies':'依赖完整性','pipeline':'图像推理接口','enhancer':'提示词增强接口','gpu':'GPU 加速'}.get(name,LABELS.get(name,name))
            key=name if name not in PACKAGES else 'package:'+name
            yield record(key,title,'checking','正在检测…',name!='enhancer')
            futures.append(pool.submit(inspect,name))
        for future in as_completed(futures):
            yield future.result()
    curl = shutil.which('curl.exe') or shutil.which('curl')
    yield record('curl', '模型下载工具', 'pass' if curl else 'fail', 'curl' if curl else '未找到 curl，请修复系统下载工具。')
    try:
        client = opener or build_opener(ProxyHandler({}))
        with client.open(Request('http://127.0.0.1:11434/api/tags'), timeout=3) as response:
            models = json.load(response).get('models', [])
        yield record('ollama', 'Ollama 对话', 'pass' if models else 'optional', '已连接本机 Ollama' if models else '先在 Ollama 下载一个聊天模型；不影响生图。', False)
    except Exception:
        yield record('ollama', 'Ollama 对话', 'optional', '未连接 Ollama；不影响生图。', False)


def ready(items):
    required = [item for item in items.values() if item.get('required', True)]
    return bool(required) and all(item.get('state') == 'pass' for item in required)


def is_environment_error(error):
    text = str(error).lower()
    return any(fragment in text for fragment in ('no module named', 'cannot import name', 'dll load failed',
        '未检测到 gpu 加速', 'torch not compiled with cuda', 'cuda driver version is insufficient',
        'could not load library', 'no nvidia driver', 'not linked with support for mps', '未检测到可用的', '当前显卡不支持', '需要修复环境'))


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--data', type=Path)
    parser.add_argument('--check', choices=(*PACKAGES, 'dependencies', 'pipeline', 'enhancer', 'gpu', 'cuda-stack'))
    parser.add_argument('--summary', action='store_true')
    options = parser.parse_args()
    if options.check:
        try:
            emit({'ok': True, 'detail': inspect_child(options.check)})
        except Exception as error:
            emit({'ok': False, 'error': str(error)[:1500]});sys.exit(1)
    else:
        if options.data is None: parser.error('--data is required')
        items = {}
        for item in collect(options.data):
            items[item['id']] = item
            if not options.summary:emit({'type': 'check', **item})
        emit({'type': 'complete', 'ready': ready(items), **({'items':items} if options.summary else {})})
